import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wiki: [{type: 'autogenerated', dirName: 'wiki'}],
  porting: [{type: 'autogenerated', dirName: 'porting'}],
};

export default sidebars;
